// src/views/BangumiView.vue
<template>
  <div v-if="error">
    <p>{{ data }}</p>
  </div>
  <div v-else class="grid">
    <a v-for="v in data.list" :href="v.url" target="_blank" rel="noopener noreferrer">
      <BangumiCard :cover="v.cover" :title="v.title"></BangumiCard>
    </a>
    <BangumiCard v-if="loading" v-for="v in 3" :skeleton="true"></BangumiCard>
  </div>
</template>

<script>
import request from "umi-request";
import config from "../../config";
import BangumiCard from "../components/BangumiCard.vue";
export default {
  data() {
    return {
      data: "",
      page: 1,
      loading: true,
      error: false,
    };
  },
  mounted() {
    request(
      "/bili/x/space/bangumi/follow/list?type=1&pn=" +
        this.page +
        "&ps=15&vmid=" +
        config.BilibiliUid,
      {
        headers: {
          referer: "https://www.bilibili.com/",
        },
      }
    )
      .then((res) => {
        this.data = res.data;
        this.data.list.forEach(e => {
          e.cover = e.cover.replace("http","https")
        });
        this.loading = false;
      })
      .catch((err) => {
        this.error = true;
        this.data = err;
        console.log(err);
        this.loading = false;
      });
  },
  components: { BangumiCard },
};
</script>

<style>
.grid {
  display: grid;
  grid-template-columns: 33.33% 33.33% 33.33%;
}
a {
  color: #3d3d3d;
}
a:hover {
  color: #3d3d3d;
}
@media (max-width: 1024px) {
  .grid {
    grid-template-columns: 50% 50%;
  }
}
</style>

// src/view/BangumiView.tsx
import { Film } from "lucide-react";
import { useEffect, useState } from "react";
import request from "umi-request";
import config from "../../config";
import Title from "../components/Title";

export default function BangumiView() {
    const { BilibiliUid } = config
    const [bangumis, setBangumis] = useState<BangumiCardProps[]>([])
    const [loading, setLoading] = useState<boolean>(true)
    const [error, setError] = useState<Error>()

    let page = 1
    useEffect(() => {
        request(`/bili/x/space/bangumi/follow/list?type=1&pn=${page}&ps=15&vmid=${BilibiliUid}`)
            .then((res) => {
                if (res && res.code == 0) {
                    setBangumis(res.data.list)
                    return
                } else {
                    setError(res.message)
                }
            }).catch((err) => {
                setError(err)
            }).finally(() => {
                setLoading(false)
            })
    }, [])
    return (
        <>
            <Title icon={<Film size={30} />} href={`https://space.bilibili.com/${BilibiliUid}`} >Bangumi</Title>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                {
                    bangumis.map((bangumi, index) => (
                        <BangumiCard key={index} {...bangumi} />
                    ))
                }
                {
                    loading ? <Skeletons></Skeletons> : error ? <div >{error.message}</div> : !bangumis.length ? <Skeletons></Skeletons> : null
                }
            </div>
        </>
    )
}

interface BangumiCardProps {
    title: string
    cover: string
    url: string
}


function BangumiCard(props: BangumiCardProps) {
    return (
        <a href={props.url} title={props.title}>
            <img
                src={props.cover}
                alt={props.title}
                className="mb-2 rounded-xl hover:ring-4 hover:ring-slate-400 transition-all"
                referrerPolicy="no-referrer" />
            <h2 className="break-all flex items-center mb-3"> {props.title} </h2>
        </a>
    )
}

function Skeletons() {
    return (
        <>
            <Skeleton></Skeleton>
            <Skeleton></Skeleton>
            <Skeleton></Skeleton>
        </>
    )
}

function Skeleton() {
    return (
        <div className="animate-pulse">
            <div className="h-52 md:h-80 w-full bg-gray-200 rounded-xl dark:bg-gray-700 mb-4"></div>
            <div className="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-1/2 mb-4"></div>
        </div>
    )
}
