// src/views/BlogView.vue
<script setup lang="ts">

import { ref, onMounted } from "vue";
import { extractFromXml } from '@extractus/feed-extractor'
import request from "umi-request";
import config from "../../config";
import HeaderTitle from "../components/HeaderTitle.vue";
import IconBook from "../components/icons/IconBook.vue";

const data = ref<any>()
const loading = ref<boolean>(true);
const error = ref<boolean>(false);

onMounted(() => {
    request
        .get(config.BlogRSS)
        .then((res) => {
            data.value = (extractFromXml(res) as any).entries;
            loading.value = false;
        })
        .catch((err) => {
            error.value = true;
            data.value = err;
            loading.value = false;
        });
})

</script>

<template>
    <div id="blog">
        <HeaderTitle>
            <h1><a :href="config.BlogUrl" target="_blank" rel="noopener noreferrer"><span>
                        <IconBook />
                    </span></a> Blog</h1>
        </HeaderTitle>
        <div v-if="error">
            <p>{{ data }}</p>
        </div>
        <div v-else>
            <div v-for="v in data" class="m-1 mb-4">
                <a :href="v.link" target="_blank">
                    <h2>
                        {{ v.title }}
                    </h2>
                    <p>{{ v.description }}</p>
                    <p style="font-size: 14px">{{ v.published.substring(0,10) }}</p>
                </a>
            </div>
            <div v-if="loading" class="skeleton m-1">
                <div style="width: 60%"></div>
                <div style="width: 90%"></div>
                <div style="width: 70%"></div>
                <div style="width: 80%"></div>
            </div>
        </div>
    </div>
</template>
  
<style scoped lang="scss">
a:hover {
    text-decoration: underline;
}
h2, p{
    word-break: break-all;
}
</style>

// src/view/BlogView.tsx
import Title from "../components/Title";
import { Book } from "lucide-react";
import config from "../../config";
import request from "umi-request";
import { extractFromXml } from '@extractus/feed-extractor'
import { useEffect, useState } from "react";
import Card from "../components/Card";
import Skeleton from "../components/Skeleton";



export default function BlogView() {
    const { BlogUrl, BlogRSS } = config
    const [blogs, setBlogs] = useState<BlogProps[]>([])
    const [error, setError] = useState<Error>()

    useEffect(() => {
        request.get(BlogRSS).then((res) => {
            setBlogs((extractFromXml(res) as any).entries)
        }).catch((err) => {
            setError(err)
        })
    }, [])

    return (
        <>
            <Title icon={<Book size={30} />} href={BlogUrl} >Blog</Title>
            {
                blogs.map((blog, index) => (
                    <BlogCard key={index} {...blog} />
                ))
            }
            {
                error ? <div >{error.message}</div> : !blogs.length ?
                    <>
                        <Skeleton className="mb-3"></Skeleton>
                        <Skeleton className="mb-3"></Skeleton>
                    </>
                    : null
            }
        </>
    )
}

interface BlogProps {
    title: string
    link: string
    published: string
    description: string
}

function BlogCard(props: BlogProps) {
    return (
        <Card className="mb-3 md:hover:scale-105 transition-all">
            <a href={props.link} target="_blank" title={props.title}>
                <h2 className="text-lg font-bold break-all flex items-center mb-3"> {props.title} </h2>
                <p className="text-gray-500 text-sm mb-3"> {props.description} </p>
                <p className="text-gray-500 text-sm mb-3"> {props.published.substring(0, 10)} </p>
            </a>
        </Card>
    )
}
