// src/views/HomeView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import MarkdownIt from "markdown-it";
import request from "umi-request";
import config from "../../config";
import IconBook from "../components/icons/IconBook.vue";
import IconGithub from "../components/icons/IconGithub.vue";
import IconTwitter from "../components/icons/IconTwitter.vue";
import IconHome from "../components/icons/IconHome.vue";
import IconYoutube from "../components/icons/IconYoutube.vue";
import IconVideo from "../components/icons/IconVideo.vue";

const data = ref<HTMLDivElement>();
const loading = ref<boolean>(true);

let md = new MarkdownIt().set({ html: true, breaks: true });

onMounted(() => {
  request
    .get(
      config.HomeMd == "Github"
        ? "https://raw.githubusercontent.com/" +
        config.GithubUsername +
        "/" +
        config.GithubUsername +
        "/master/readme.md"
        : config.HomeMd
    )
    .then((res) => {
      // (data.value as HTMLDivElement).innerHTML = md.render(res)
      data.value!.innerHTML = md.render(res);
      loading.value = false

    })
    .catch((err) => {
      data.value!.innerHTML = err;
      loading.value = false
    });
});
</script>

<template>
  <div id="home">
    <header :class="config.Style.HeaderLayout">
      <img v-if="config.Avatar" class="avatar" :src="config.Avatar" alt="avatar" />
      <div :style="{ color: config.Style.HeaderFontColor }" class="info">
        <h1>{{ config.Name }}</h1>
        <p>{{ config.Desc }}</p>
        <div class="icons">
          <a v-if="config.BlogUrl" :href="config.BlogUrl" target="_blank" title="Blog">
            <IconBook></IconBook>
          </a>
          <a v-if="config.GithubUsername" :href="'https://github.com/' + config.GithubUsername" target="_blank"
            title="Github">
            <IconGithub></IconGithub>
          </a>
          <a v-if="config.YoutubeUrl" :href="config.YoutubeUrl" target="_blank" title="Youtube">
            <IconYoutube></IconYoutube>
          </a>
          <a v-if="config.TwitterUrl" :href="config.TwitterUrl" target="_blank" title="Twitter">
            <IconTwitter></IconTwitter>
          </a>
        </div>
      </div>
    </header>
    <div class="markdown" id="home" ref="data"></div>
    <div v-if="loading" class="skeleton">
      <div style="width: 60%"></div>
      <div style="width: 90%"></div>
      <div style="width: 70%"></div>
      <div style="width: 80%"></div>
    </div>
  </div>
</template>

<style scoped lang="scss">
header {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-bottom: 63px;
  margin-top: 126px;
  transition: cubic-bezier(0.075, 0.82, 0.165, 1);

  .avatar {
    width: 140px;
    height: 140px;
    border-radius: 50%;
    object-fit: cover;
  }

  .info {
    margin-left: 28px;
    width: 310px;

    h1 {
      font-size: 36px;
      font-weight: normal;
    }

    p {
      font-size: 20px;
    }

    .icons svg {
      margin-right: 8px;
    }
  }

  &.ReverseSpace {
    justify-content: space-between;
    flex-direction: row-reverse;

    .info {
      margin-left: 0px;
    }
  }

  &.VCenter {
    flex-direction: column;
    text-align: center;
  }

  &.VCenter .info {
    margin-left: 0;
  }

  &.Left {
    justify-content: flex-start;
  }

}

@media (max-width: 1024px) {
  header {
    margin-bottom: 25px;
    flex-direction: column !important;
    text-align: center;

    .info {
      margin-left: 0;
    }
  }
}
</style>

// src/view/HomeView.tsx
import Card from "../components/Card"
import config from "../../config";
import { Github, Book, Youtube, Twitter } from "lucide-react";
import { useEffect, useState } from "react";
import request from "umi-request";
import { marked } from "marked";
import Skeleton from "../components/Skeleton";
import Animation from "../components/Animation";

export default function HomeView() {
  const { Name, Desc, HomeMD, GithubUsername, Avatar } = config;
  const [introduce, setIntroduce] = useState<string>("")
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    if (!HomeMD) {
      return
    }
    request.get(
      HomeMD === "Github" ?
        `https://raw.githubusercontent.com/${GithubUsername}/${GithubUsername}/main/readme.md`
        : HomeMD
    ).then((res) => {
      setIntroduce(marked.parse(res))
    }).catch((err) => {
      setIntroduce(err)
    }).finally(() => {
      setLoading(false)
    })
  }, [])

  return (
    <Animation id="home">
      <div className="flex flex-col justify-between items-center mb-10 p-4">
        <img src={Avatar} title={Name} className="h-32 w-32 rounded-full ring-2 ring-slate-400 mb-3" />
        <div className="text-center mt-4 md:mt-0  flex flex-col w-3/4 md:w-1/2">
          <h1 className="text-2xl font-semibold mb-2">{Name}</h1>
          <p className="text-gray-500 ">{Desc}</p>
          <div className="mt-2 flex justify-center ">
            {
              getSocialLinks().map((link, index) => (
                <IconLink key={index} href={link.href} icon={link.icon} />
              ))
            }
          </div>
        </div>
      </div>
      {
        HomeMD ?
          loading ?
            <Skeleton></Skeleton>
            :
            < Card
              className="prose prose-slate max-w-none"
              dangerouslySetInnerHTML={{ __html: introduce }} />
          : null
      }
    </Animation>
  )
}

function getSocialLinks(): { href: string, icon: JSX.Element }[] {
  const { GithubUsername, BlogUrl, YoutubeUrl, TwitterUrl } = config
  const result = []
  if (GithubUsername) {
    result.push({
      href: `https://github.com/${GithubUsername}`,
      icon: <Github />,
    })
  }

  if (BlogUrl) {
    result.push({
      href: BlogUrl,
      icon: <Book />,
    })
  }

  if (YoutubeUrl) {
    result.push({
      href: YoutubeUrl,
      icon: <Youtube />,
    })
  }

  if (TwitterUrl) {
    result.push({
      href: TwitterUrl,
      icon: <Twitter />,
    })
  }

  return result;
}

function IconLink({ href, icon }: { href: string, icon: JSX.Element }) {
  return (
    <a
      className="m-1 md-0 p-1 border rounded-lg bg-slate-200 hover:bg-slate-300"
      href={href} target="_blank" rel="noreferrer">
      {icon}
    </a>
  )
}
